services:

# Strip CLI Config
  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    volumes:
      - stripe-config:/root/.config/stripe
    command: listen --forward-to host.docker.internal:8080/api/stripe/webhook
    restart: unless-stopped
    networks:
      - lovable-net

# PG Vector DB Config
  pgvector:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: pgvector-db-lovable
    environment:
      POSTGRES_DB: pgvector-test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "9010:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql
    restart: unless-stopped
    networks:
      - lovable-net

# Minio config
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-lovable
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped
    networks:
      - lovable-net

volumes:
  pgvector-data:
  minio-data:
  stripe-config:

networks:
  lovable-net:
    driver: bridge

