spring:
  application:
    name: loveable-clone

  datasource:
    url: jdbc:postgresql://localhost:5432/loveable_db
    username: postgres
    password: postgres

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # dev only
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

jwt:
  secret-key: 32q4dasnbd17i623kjedfbn23qy4hfwsj

stripe:
  secret: sk_test_51SymwUC72Uou9fu629JOxeDtbLVFJpYFzwgieFQGszecE2guOcWgC7erKlnLhOR4OScx5K8brEHlW1oa5UXQ3q8600YJIEkXQf
  webhook:
    secret: whsec_f779b4640b39d07046f0235ad13d6b57368055481f1756d921f78bd25a5c49b5

client:
  url: http://localhost:8080
