apiVersion: apps/v1
kind: Deployment
metadata:
  name: shuttle-proxy
  namespace: shuttle-apps
  labels:
    app: shuttle-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shuttle-proxy
  template:
    metadata:
      name: shuttle-proxy
      labels:
        app: shuttle-proxy
    spec:
      containers:
        - name: proxy
          image: abhishekumap/proxy
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
          env:
            - name: REDIS_URL
              value: "redis://redis-service:6379"
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: shuttle-proxy-svc
  namespace: shuttle-apps
spec:
  selector:
    app: shuttle-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

      